PARTIES = [
    "PSUV",
    "PCV",
    "TUPAMARO",
    "PPT",
    "MSV",
    "PODEMOS",
    "MEP",
    "APC",
    "ORA",
    "UPV",
    "EV",
    "PVV",
    "PFV",
    "AD",
    "COPEI",
    "MR",
    "BR",
    "DDP",
    "UNE",
    "EL_CAMBIO",
    "PV",
    "VU",
    "UVV",
    "MPJ",
    "AP",
    "MOVEV",
    "CMC",
    "FV",
    "ALIANZA_DEL_LAPIZ",
    "MIN_UNIDAD",
    "SPV",
    "VPA",
    "AREPA",
    "UNTC",
    "MPV",
    "MUD",
    "CENTRADOS",
    "CONDE",
]

MADURO_PARTIES = PARTIES[:13]
LUIS_MARTINEZ_PARTIES = PARTIES[13:19]
BERTUCCI_PARTIES = PARTIES[19:20]
JOSE_BRITO_PARTIES = PARTIES[20:24]
ANTONIO_ECARRI_PARTIES = PARTIES[24:30]
CLAUDIO_FERMIN_PARTIES = PARTIES[30:31]
DANIEL_CEBALLOS_PARTIES = PARTIES[31:33]
EDMUNDO_GONZALEZ_PARTIES = PARTIES[33:36]
BENJAMIN_RAUSSEO_PARTIES = PARTIES[36:37]
